spring:
    application:
        name: MyApp

    datasource:
        url: jdbc:postgresql://localhost:5432/app_dev
        driver-class-name: org.postgresql.Driver
        username: ${DEV_DB_USER}
        password: ${DEV_DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    jackson:
        deserialization:
            fail-on-unknown-properties: false
    cloud:
        openfeign:
            client:
                config:
                    default:
                        logger-level: BASIC

server:
    servlet:
        context-path: /api
logging:
    level:
        <com.app.MyApp.api>: debug

app:
    jwt:
        secret: ${JWT_SECRET_KEY}
        expiration-ms: 3600000
