spring:
    application:
        name: NextWatch

    datasource:
        driver-class-name: org.postgresql.Driver

    jackson:
        deserialization:
            fail-on-unknown-properties: false

    ai:
        ollama:
            embedding:
                model: nomic-embed-text:v1.5
        vectorstore:
            pgvector:
                dimensions: 768

server:
    servlet:
        context-path: /api

app:
    jwt:
        secret: ${JWT_SECRET_KEY}
        expiration-ms: 3600000
